name: Test Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tox_env:
          - "pylint"
          - "flake8"
    steps:
    - name: Check out the repo
      uses: actions/checkout@v1
    - name: Run tox
      uses: fedora-python/tox-github-action@v0.4
      with:
        tox_env: ${{ matrix.tox_env }}
